apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8000
  # type: LoadBalancer  # kubectl doesn't support LoadBalancer. So, use NodePort for local access and forward the port     
  type: NodePort
